import { 
  Users, BookOpen, Sparkles, Server, 
  FileText, File, Shield, Edit, Archive, BadgeAlert 
} from 'lucide-react';
import { KpiMetric, DocumentStat, ActivityUpdate } from '../lib/types';

export const kpiData: KpiMetric[] = [
  {
    id: '1',
    title: 'Tổng người dùng',
    value: '128',
    changeLabel: '+5 tuần này',
    changeType: 'positive',
    icon: Users,
    iconWrapperClass: 'bg-blue-100',
    iconClass: 'text-blue-600',
  },
  {
    id: '2',
    title: 'Thư viện tài liệu',
    value: '45',
    changeLabel: '3 chờ index',
    changeType: 'warning',
    icon: BookOpen,
    iconWrapperClass: 'bg-amber-100',
    iconClass: 'text-amber-600',
  },
  {
    id: '3',
    title: 'Truy vấn AI',
    value: '1.2k',
    changeLabel: 'High usage',
    changeType: 'neutral',
    icon: Sparkles,
    iconWrapperClass: 'bg-orange-100',
    iconClass: 'text-orange-600',
  },
  {
    id: '4',
    title: 'Trạng thái máy chủ',
    value: 'Operational',
    changeType: 'status',
    statusText: 'Hoạt động',
    icon: Server,
    iconWrapperClass: 'bg-emerald-100',
    iconClass: 'text-emerald-700',
  },
];

export const topDocuments: DocumentStat[] = [
  {
    id: 'doc1',
    title: 'Chính sách nghỉ phép HR-05',
    tags: ['HR', 'Vận hành'],
    icon: FileText,
    iconWrapperClass: 'bg-red-50',
    iconClass: 'text-red-600',
    views: 452,
    trendPercentage: 12,
    trendType: 'up',
    sparklinePath: 'M0,25 L10,22 L20,28 L30,15 L40,18 L50,10 L60,12 L70,5 L80,8 L90,2 L100,5',
  },
  {
    id: 'doc2',
    title: 'Quy trình vận hành QT-01',
    tags: ['QT', 'Sản xuất'],
    icon: File,
    iconWrapperClass: 'bg-blue-50',
    iconClass: 'text-blue-600',
    views: 388,
    trendPercentage: 8,
    trendType: 'up',
    sparklinePath: 'M0,28 L15,20 L30,22 L45,12 L60,15 L75,8 L90,10 L100,2',
  },
  {
    id: 'doc3',
    title: 'Sổ tay an toàn lao động v2',
    tags: ['Safety'],
    icon: FileText,
    iconWrapperClass: 'bg-red-50',
    iconClass: 'text-red-600',
    views: 310,
    trendPercentage: 0,
    trendType: 'steady',
    sparklinePath: 'M0,10 L20,15 L40,5 L60,18 L80,12 L100,15',
  },
  {
    id: 'doc4',
    title: 'Hướng dẫn thiết lập VPN',
    tags: ['IT', 'Security'],
    icon: Shield,
    iconWrapperClass: 'bg-blue-50',
    iconClass: 'text-blue-600',
    views: 215,
    trendPercentage: 24,
    trendType: 'up',
    sparklinePath: 'M0,25 L15,20 L30,22 L45,10 L60,5 L75,12 L90,18 L100,15',
  },
  {
    id: 'doc5',
    title: 'Chính sách bảo mật IT-04',
    tags: ['IT'],
    icon: FileText,
    iconWrapperClass: 'bg-red-50',
    iconClass: 'text-red-600',
    views: 168,
    trendPercentage: 5,
    trendType: 'up',
    sparklinePath: 'M0,28 L20,25 L40,22 L60,18 L80,12 L100,5',
  },
];

export const recentUpdates: ActivityUpdate[] = [
  {
    id: 'up1',
    title: 'QT-01 cập nhật v2.0',
    author: 'Admin X',
    time: '2 giờ trước',
    icon: FileText,
    iconWrapperClass: 'bg-slate-900',
    iconClass: 'text-white',
  },
  {
    id: 'up2',
    title: 'Chính sách bảo mật mới',
    author: 'Hệ thống',
    time: '5 giờ trước',
    icon: Edit,
    iconWrapperClass: 'bg-blue-100',
    iconClass: 'text-blue-700',
  },
  {
    id: 'up3',
    title: 'Lưu trữ tài liệu dự án A',
    author: 'Trung N.',
    time: '1 ngày trước',
    icon: Archive,
    iconWrapperClass: 'bg-indigo-100',
    iconClass: 'text-indigo-700',
  },
  {
    id: 'up4',
    title: 'HD-05 được thêm mới',
    author: 'Admin Y',
    time: '2 ngày trước',
    icon: BadgeAlert,
    iconWrapperClass: 'bg-amber-100',
    iconClass: 'text-amber-700',
  },
  {
    id: 'up5',
    title: 'Sổ tay nhân viên v1.4',
    author: 'Nhân sự',
    time: '3 ngày trước',
    icon: FileText,
    iconWrapperClass: 'bg-slate-900',
    iconClass: 'text-white',
  },
  {
    id: 'up6',
    title: 'Quy định trang phục v2',
    author: 'HR',
    time: '4 ngày trước',
    icon: FileText,
    iconWrapperClass: 'bg-slate-900',
    iconClass: 'text-white',
  },
  {
    id: 'up7',
    title: 'Báo cáo tài chính Q3',
    author: 'Kế toán',
    time: '5 ngày trước',
    icon: Archive,
    iconWrapperClass: 'bg-indigo-100',
    iconClass: 'text-indigo-700',
  },
  {
    id: 'up8',
    title: 'Hướng dẫn PCCC',
    author: 'Admin Z',
    time: '1 tuần trước',
    icon: BadgeAlert,
    iconWrapperClass: 'bg-amber-100',
    iconClass: 'text-amber-700',
  },
];
